// <auto-generated />
using System;
using Auditiva_Netcore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuditivaNetcore.Migrations
{
    [DbContext(typeof(AuditivaContext))]
    [Migration("20191210074021_AuditivaDB")]
    partial class AuditivaDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CalificacionesItem", b =>
                {
                    b.Property<string>("CalificacionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CIdentificacion");

                    b.Property<string>("NotaActividad");

                    b.Property<string>("NumbActividad");

                    b.Property<string>("TitleTema");

                    b.HasKey("CalificacionId");

                    b.ToTable("CalificacionesItems");
                });

            modelBuilder.Entity("CursoItem", b =>
                {
                    b.Property<string>("CursoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PApellidos");

                    b.Property<string>("PGrado");

                    b.Property<string>("PNombres");

                    b.Property<string>("PTipo");

                    b.HasKey("CursoId");

                    b.ToTable("CursoItems");
                });

            modelBuilder.Entity("ProfesorItem", b =>
                {
                    b.Property<string>("Identificacion")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Correo");

                    b.Property<DateTime>("FechaNacimento");

                    b.Property<string>("Genero");

                    b.Property<string>("Grado");

                    b.Property<string>("Nombres");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Telefono");

                    b.Property<string>("Tipo");

                    b.HasKey("Identificacion");

                    b.ToTable("ProfesorItems");
                });
#pragma warning restore 612, 618
        }
    }
}
